package com.bigboxer23.generationMeter;

/** */
public interface TestConstants {

	String device1Name = "Test generator 1";
	String device1Xml = "<DAS>\n"
			+ "<mode>LOGFILEUPLOAD</mode>"
			+ "<name>xx1xx6xxxxxx</name>\n"
			+ "<serial>xx1xx6xxxxxx</serial>\n"
			+ "<devices>\n"
			+ "<device>\n"
			+ "<name>"
			+ device1Name
			+ "</name>\n"
			+ "<address>12</address>\n"
			+ "<type>Veris Hxxxx-xxxx-x, Full-Data, Modbus, xxx Amp</type>\n"
			+ "<class>2</class>\n"
			+ "<status>Ok</status>\n"
			+ "<numpoints>26</numpoints>\n"
			+ "<records>\n"
			+ "<record>\n"
			+ "<time zone=\"UTC\">2021-08-21 00:51:10</time>\n"
			+ "<age units=\"seconds\">1</age>\n"
			+ "<error text=\"Ok\">0</error>\n"
			+ "<point number=\"0\" name=\"Energy Consumption\" units=\"kWh\""
			+ " value=\"7675835.50\"/>\n"
			+ "<point number=\"1\" name=\"Real Power\" units=\"kW\" value=\"6.219\"/>\n"
			+ "<point number=\"2\" name=\"Reactive Power\" units=\"kVAR\""
			+ " value=\"8.781\"/>\n"
			+ "<point number=\"3\" name=\"Apparent Power\" units=\"kVA\""
			+ " value=\"10.750\"/>\n"
			+ "<point number=\"4\" name=\"Power Factor\" units=\"\" value=\"0.5774\"/>\n"
			+ "<point number=\"5\" name=\"Voltage, Line to Line\" units=\"Volts\""
			+ " value=\"486.2\"/>\n"
			+ "<point number=\"6\" name=\"Voltage, Line to Neutral\" units=\"Volts\""
			+ " value=\"281.7\"/>\n"
			+ "<point number=\"7\" name=\"Current\" units=\"Amps\" value=\"12.7\"/>\n"
			+ "<point number=\"8\" name=\"Real Power phase A\" units=\"kW\""
			+ " value=\"1.891\"/>\n"
			+ "<point number=\"9\" name=\"Real Power phase B\" units=\"kW\""
			+ " value=\"2.258\"/>\n"
			+ "<point number=\"10\" name=\"Real Power phase C\" units=\"kW\""
			+ " value=\"2.055\"/>\n"
			+ "<point number=\"11\" name=\"Power Factor phase A\" units=\"\""
			+ " value=\"0.5278\"/>\n"
			+ "<point number=\"12\" name=\"Power Factor phase B\" units=\"\""
			+ " value=\"0.6138\"/>\n"
			+ "<point number=\"13\" name=\"Power Factor phase C\" units=\"\""
			+ " value=\"0.5971\"/>\n"
			+ "<point number=\"14\" name=\"Voltage phase A-B\" units=\"Volts\""
			+ " value=\"486.3\"/>\n"
			+ "<point number=\"15\" name=\"Voltage phase B-C\" units=\"Volts\""
			+ " value=\"485.8\"/>\n"
			+ "<point number=\"16\" name=\"Voltage phase C-A\" units=\"Volts\""
			+ " value=\"486.3\"/>\n"
			+ "<point number=\"17\" name=\"Voltage phase A-N\" units=\"Volts\""
			+ " value=\"282.2\"/>\n"
			+ "<point number=\"18\" name=\"Voltage phase B-N\" units=\"Volts\""
			+ " value=\"281.5\"/>\n"
			+ "<point number=\"19\" name=\"Voltage phase C-N\" units=\"Volts\""
			+ " value=\"281.3\"/>\n"
			+ "<point number=\"20\" name=\"Current phase A\" units=\"Amps\""
			+ " value=\"12.6\"/>\n"
			+ "<point number=\"21\" name=\"Current phase B\" units=\"Amps\""
			+ " value=\"13.1\"/>\n"
			+ "<point number=\"22\" name=\"Current phase C\" units=\"Amps\""
			+ " value=\"12.3\"/>\n"
			+ "<point number=\"23\" name=\"Average Demand\" units=\"kW\""
			+ " value=\"6.563\"/>\n"
			+ "<point number=\"24\" name=\"Minimum Demand\" units=\"kW\""
			+ " value=\"5.844\"/>\n"
			+ "<point number=\"25\" name=\"Maximum Demand\" units=\"kW\""
			+ " value=\"7.938\"/>\n"
			+ "</record>\n"
			+ "</records>\n"
			+ "</device>\n"
			+ "</devices>\n"
			+ "</DAS>";
}
